---
- name: apt installer
  hosts: ubuntu
  become: true
  tasks:
    - name: install packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apache2
        - cron

